version: '3.1'

services:
  wordpress:
    build: .
    restart: always
    networks:
      - nginx_default
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
      WP_REDIS_HOST: redis
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql
    restart: always
    networks:
      - nginx_default
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    networks:
      - nginx_default
    volumes:
      - redis:/data

volumes:
  wordpress:
  db:
  redis:

networks:
  nginx_default:
    external: true